use Dingo;

insert into restoran(naziv_restorana, ukupan_broj_stolova, grad, adresa) values
('Zapata', 40, 'Beograd', 'Vojvode Bogdana 13'),
('Marukoshi Restaurant and Bar', 35, 'Beograd','Kapetan Mišina 37'),
('Cantina De Frida', 20, 'Beograd', 'Karađorđeva 2'),
('Byblos Cuisine Lebanese', 30, 'Beograd', 'Hadži Milentijeva 70'),
('Restoran Istok', 35, 'Beograd', 'Gospodar Jevremova 50'),
('Le Molière', 20, 'Beograd', 'Zmaj Jovina 11'),
('Smokvica', 30, 'Beograd', 'Gospodar Jovanova 45'),
('Smokvica', 25 , 'Beograd', 'Kralja Petra 56'),
('alla Lanterna', 40, 'Novi Sad', 'Dunavska 27'),
('Korpa Deli Market i Bistro', 30, 'Novi Sad', 'Veselina Masleše 2'),
('Zuwar Belgrade Restaurant', 15, 'Beograd', 'Đure Jakšića 3'), 
('Salon 1905', 25, 'Beograd', 'Karađorđeva 48'),
('Bizu Restoran', 20, 'Beograd', 'Bizu Restoran'),
('Sakura', 30, 'Beograd', 'Karađorđeva 2-4'),
('Steakhouse El Toro', 15, 'Beograd', 'Masarikova 5'),
('Gušti Mora', 18, 'Beograd', 'Radnička 27'),
('Langouste Restaurant', 16, 'Beograd', 'Kosančićev venac 29'),
('Restoran Terasa', 28, 'Novi Sad', 'Petrovaradinska tvrđava'),
('Little Bay', 25, 'Beograd', 'Dositejeva 9a'),
('Franš', 40, 'Beograd', 'Bulevar oslobođenja 18a')
;

insert into restoran_vrsta_hrane(vrsta_hrane, id_restorana) values
('meksička', 1),
('vegeterijanska', 1),
('japanska', 2),
('vegeterijanska', 2),
('veganska', 2),
('španska', 3),
('vegeterijanska', 3),
('veganska', 3),
('libanska', 4),
('mediteranska', 4),
('vegeterijanska', 4),
('veganska', 4),
('bez glutena', 4),
('vijetnamska', 5),
('vegeterijanska', 5),
('veganska', 5),
('bez glutena', 5),
('francuska', 6),
('vegeterijanska', 6),
('kafe', 7),
('mediteranska', 7),
('zdrava hrana', 7),
('vegeterijanska', 7),
('veganska', 7),
('bez glutena', 7),
('kafe', 8),
('mediteranska', 8),
('zdrava hrana', 8),
('vegeterijanska', 8),
('veganska', 8),
('bez glutena', 8),
('italijanska', 9),
('mediteranska', 9),
('vegeterijanska', 9),
('veganska', 9),
('italijanska', 10),
('kafe', 10),
('libanska', 11),
('arapska', 11),
('vegeterijanska', 11),
('veganska', 11),
('halal', 11),
('francuska', 12),
('italijanska', 12),
('mediteranska', 12),
('vegeterijanska', 12),
('veganska', 12),
('bez glutena', 12),
('japanska', 13),
('suši', 13),
('vegeterijanska', 13),
('japanska', 14),
('veganska', 14),
('vegeterijanska', 14),
('veganska', 14),
('latinoamerička', 15),
('španska', 15),
('roštilj', 15),
('međunarodna', 15),
('morska', 16),
('mediteranska', 16),
('vegeterijanska', 16),
('međunarodna', 17),
('morska', 17),
('mediteranska', 17),
('vegeterijanska', 17),
('veganska', 17),
('mediteranska', 18),
('evropska', 18),
('vegeterijanska', 18),
('veganska', 18),
('međunarodna', 19),
('vegeterijanska', 19),
('veganska', 19),
('bez glutena', 19),
('mediteranska', 20),
('evropska', 20),
('međunarodna', 20),
('vegeterijanska', 20),
('veganska', 20),
('bez glutena', 20)
;


insert ignore into vrsta_hrane(vrsta_hrane) values
('meksička'),
('vegeterijanska'),
('japanska'),
('vegeterijanska'),
('veganska'),
('španska'),
('vegeterijanska'),
('veganska'),
('libanska'),
('mediteranska'),
('vegeterijanska'),
('veganska'),
('bez glutena'),
('vijetnamska'),
('vegeterijanska'),
('veganska'),
('bez glutena'),
('francuska'),
('vegeterijanska'),
('kafe'),
('mediteranska'),
('zdrava hrana'),
('vegeterijanska'),
('veganska'),
('bez glutena'),
('kafe'),
('mediteranska'),
('zdrava hrana'),
('vegeterijanska'),
('veganska'),
('bez glutena'),
('italijanska'),
('mediteranska'),
('vegeterijanska'),
('veganska'),
('italijanska'),
('kafe'),
('libanska'),
('arapska'),
('vegeterijanska'),
('veganska'),
('halal'),
('francuska'),
('italijanska'),
('mediteranska'),
('vegeterijanska'),
('veganska'),
('bez glutena'),
('japanska'),
('suši'),
('vegeterijanska'),
('japanska'),
('veganska'),
('vegeterijanska'),
('veganska'),
('latinoamerička'),
('španska'),
('roštilj'),
('međunarodna'),
('morska'),
('mediteranska'),
('vegeterijanska'),
('međunarodna'),
('morska'),
('mediteranska'),
('vegeterijanska'),
('veganska'),
('mediteranska'),
('evropska'),
('vegeterijanska'),
('veganska'),
('međunarodna'),
('vegeterijanska'),
('veganska'),
('bez glutena'),
('mediteranska'),
('evropska'),
('međunarodna'),
('vegeterijanska'),
('veganska'),
('bez glutena')
;

